name: geovoy_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  web_socket_channel: ^2.4.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.5.0
  lottie: ^2.7.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5
  geolocator: ^10.1.0
  flutter_launcher_icons: ^0.13.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  screen_protector: ^1.4.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/backgrounds/icono.jpeg"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/backgrounds/
    - assets/images/logos/
    - assets/images/icons/
    - assets/animations/